language: node_js

node_js:
  - "0.10"

install:
  - npm install

script: gulp test

after_success:
  - cat ./coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls.js; rm -rf ./coverage

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/24ef0a3dc30496785dbb
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

  slack:
    rooms:
      - teamikl:KWPPDyGWSgf8QUUDQG429c93#ninjam
