language: node_js

node_js:
  - "0.10"

install: npm install

script: npm test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/24ef0a3dc30496785dbb
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

  slack:
    rooms:
      - teamikl:KWPPDyGWSgf8QUUDQG429c93#ninjam
